### ISSUE TITLE
Aqara G2 not work

### ISSUE THREAD

**Issue by Ener-G** [miguelangel-nubla/videoP2Proxy#13]
Hey,

my new camera "Aqara Hub G2" will not work :(

```
root@raspberrypi:~# videop2proxy --ip 192.168.86.6 --token TOKENXXXXXX --rtsp 8554
Starting proxy...
Starting RTSP server on "rtsp://192.168.86.2:8554/"
(Using port 80 for optional RTSP-over-HTTP tunneling.)

Got error when receiving: timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 259, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 259, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 259, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 259, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 290, in send
    return self.send(command, parameters, retry_count - 1)
  File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 290, in send
    return self.send(command, parameters, retry_count - 1)
  File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 290, in send
    return self.send(command, parameters, retry_count - 1)
  File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 293, in send
    raise DeviceException("No response from the device") from ex
miio.exceptions.DeviceException: No response from the device
Can't read output line 1 from command: python3 -c "import miio;result = miio.device.Device('192.168.86.6', 'TOKENXXXXXX').send('get_ipcprop', ['all']);print(result['p2p_id']);print(result['avID']);print(result['avPass']);"
Error connecting to camera, make sure ip and token are correct.
Error, waiting 10 seconds and trying again.
```

**Comment by ghost** [comment]
perhaps it should be interesting to share info.
[https://github.com/rytilahti/python-miio/issues/504](url)

Actually there is no p2p_id for the streaming of the video but information mention a video_stream property....

**Comment by BaQs** [comment]
Same issue here. What kind of info do you need ?

**Comment by lpawlak** [comment]
> 
> 
> Hey,
> 
> my new camera "Aqara Hub G2" will not work :(
> 
> ```
> root@raspberrypi:~# videop2proxy --ip 192.168.86.6 --token TOKENXXXXXX --rtsp 8554
> Starting proxy...
> Starting RTSP server on "rtsp://192.168.86.2:8554/"
> (Using port 80 for optional RTSP-over-HTTP tunneling.)
> 
> Got error when receiving: timed out
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 259, in send
>     data, addr = s.recvfrom(1024)
> socket.timeout: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 259, in send
>     data, addr = s.recvfrom(1024)
> socket.timeout: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 259, in send
>     data, addr = s.recvfrom(1024)
> socket.timeout: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 259, in send
>     data, addr = s.recvfrom(1024)
> socket.timeout: timed out
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 290, in send
>     return self.send(command, parameters, retry_count - 1)
>   File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 290, in send
>     return self.send(command, parameters, retry_count - 1)
>   File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 290, in send
>     return self.send(command, parameters, retry_count - 1)
>   File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 293, in send
>     raise DeviceException("No response from the device") from ex
> miio.exceptions.DeviceException: No response from the device
> Can't read output line 1 from command: python3 -c "import miio;result = miio.device.Device('192.168.86.6', 'TOKENXXXXXX').send('get_ipcprop', ['all']);print(result['p2p_id']);print(result['avID']);print(result['avPass']);"
> Error connecting to camera, make sure ip and token are correct.
> Error, waiting 10 seconds and trying again.
> ```

Have the same problem :(

**Comment by Letalis** [comment]
is this project dead?
I encounter the same issue as people above.

**Comment by meeDamian** [comment]
Same issue here.
