### ISSUE TITLE
Xiaomi Mijia-720P dont works

### ISSUE THREAD

**Issue by segalion** [miguelangel-nubla/videoP2Proxy#2]
Xiaomi Mijia-720P camera with latest firm: 3.3.6_2018062014

```
Starting proxy...
Starting RTSP server on "rtsp://192.168.1.2:8554/"
(Using port 8000 for optional RTSP-over-HTTP tunneling.)

Got error when receiving: timed out
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/miio/device.py", line 257, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/miio/device.py", line 257, in send

    data, addr = s.recvfrom(1024)
socket.timeout: timed out
...
```

xiaomi gateway camera works fine!!!

**Comment by liaanvdm** [comment]
I just tried with the Xiaomi Mijia 1080P V3 (the all white version) and I get exactly the same timeout error as segalion. Such a pity.

**Comment by xiaodoudou** [comment]
Did try on several camera:

# chuangmi.camera.xiaobai
```
Starting proxy...
Unable to discover a device at address 172.20.30.119
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 224, in send
    self.do_discover()
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 162, in do_discover
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 172.20.30.119
Can't read output line 1 from command: python3 -c "import miio;result = miio.device.Device('[redacted]', '[redacted]').send('get_ipcprop', ['all']);print(result['p2p_id']);print(result['avID']);print(result['avPass']);"
Error connecting to camera, make sure ip and token are correct.
Error, waiting 10 seconds and trying again.
```
Setting that I got from MiHome for that camera:

```
{
			"did": "[REDACTED]",
			"token": "[REDACTED]",
			"longitude": "0.00000000",
			"latitude": "0.00000000",
			"name": "Caméra chambre Ethan",
			"pid": "0",
			"localip": "[REDACTED]",
			"mac": "[REDACTED]",
			"ssid": "[REDACTED]",
			"bssid": "[REDACTED]",
			"parent_id": "",
			"parent_model": "",
			"show_mode": 1,
			"model": "chuangmi.camera.xiaobai",
			"adminFlag": 1,
			"shareFlag": 0,
			"permitLevel": 16,
			"isOnline": true,
			"desc": "Camera online",
			"extra": {
				"isSetPincode": 0,
				"fw_version": "3.3.10_2018061309",
				"needVerifyCode": 0,
				"isPasswordEncrypt": 0
			},
			"uid": 1201287773,
			"pd_id": 75,
			"password": "",
			"p2p_id": "",
			"rssi": 0,
			"family_id": 0,
			"reset_flag": 0
		}
```


#isa.camera.isc5c1
```
Starting proxy...
Unable to discover a device at address 172.20.30.169
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 224, in send
    self.do_discover()
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 162, in do_discover
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 172.20.30.169
Can't read output line 1 from command: python3 -c "import miio;result = miio.device.Device('[redacted]', '[redacted]').send('get_ipcprop', ['all']);print(result['p2p_id']);print(result['avID']);print(result['avPass']);"
Error connecting to camera, make sure ip and token are correct.
Error, waiting 10 seconds and trying again.
```
Setting that I got from MiHome for that camera:

```
{
			"did": "[REDACTED]",
			"token": "[REDACTED]",
			"longitude": "0.00000000",
			"latitude": "0.00000000",
			"name": "Caméra Balcon Ethan",
			"pid": "0",
			"localip": "[REDACTED]",
			"mac": "[REDACTED]",
			"ssid": "[REDACTED]",
			"bssid": "[REDACTED]",
			"parent_id": "",
			"parent_model": "",
			"show_mode": 1,
			"model": "isa.camera.isc5c1",
			"adminFlag": 1,
			"shareFlag": 0,
			"permitLevel": 16,
			"isOnline": true,
			"desc": "Device online ",
			"extra": {
				"isSetPincode": 0,
				"fw_version": "5.6.2.138",
				"needVerifyCode": 0,
				"isPasswordEncrypt": 0
			},
			"uid": 1201287773,
			"pd_id": 434,
			"password": "",
			"p2p_id": "",
			"rssi": -56,
			"family_id": 0,
			"reset_flag": 0
		}
```
