### ISSUE TITLE
Timed out or not responding

### ISSUE THREAD

**Issue by cotarelo** [miguelangel-nubla/videoP2Proxy#24]
Hi Miguel Angel, 

I am trying to run it on a Xiaomi home Basic 1080 ( mijia_v3 ). It seems to be connecting correctly since there's an initial waiting for the error, but it does not seem to connect. The IP address of the camera and the token should be correct

```$ ./videop2proxy --ip X.X.X.X --token myHexadecimalTokenGoesHere --rtsp 8554
Starting proxy...
Starting RTSP server on "rtsp://X.X.X.X:8554/"
(Using port 8000 for optional RTSP-over-HTTP tunneling.)

Got error when receiving: timed out
Traceback (most recent call last):
  File "/home/dietpi/.local/lib/python3.7/site-packages/miio/miioprotocol.py", line 192, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dietpi/.local/lib/python3.7/site-packages/miio/miioprotocol.py", line 192, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dietpi/.local/lib/python3.7/site-packages/miio/miioprotocol.py", line 192, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dietpi/.local/lib/python3.7/site-packages/miio/miioprotocol.py", line 192, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dietpi/.local/lib/python3.7/site-packages/miio/device.py", line 147, in send
    command, parameters, retry_count, extra_parameters=extra_parameters
  File "/home/dietpi/.local/lib/python3.7/site-packages/miio/miioprotocol.py", line 236, in send
    extra_parameters=extra_parameters,
  File "/home/dietpi/.local/lib/python3.7/site-packages/miio/miioprotocol.py", line 236, in send
    extra_parameters=extra_parameters,
  File "/home/dietpi/.local/lib/python3.7/site-packages/miio/miioprotocol.py", line 236, in send
    extra_parameters=extra_parameters,
  File "/home/dietpi/.local/lib/python3.7/site-packages/miio/miioprotocol.py", line 240, in send
    raise DeviceException("No response from the device") from ex
miio.exceptions.DeviceException: No response from the device
Can't read output line 1 from command: python3 -c "import miio;result = miio.device.Device('192.168.31.11', '6c38646e535433383050547448626350').send('get_ipcprop', ['all']);print(result['p2p_id']);print(result['avID']);print(result['avPass']);"
Error connecting to camera, make sure ip and token are correct.
Error, waiting 10 seconds and trying again.
^CTraceback (most recent call last):
  File "/home/dietpi/.local/lib/python3.7/site-packages/miio/miioprotocol.py", line 192, in send

    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
$   File "/home/dietpi/.local/lib/python3.7/site-packages/miio/device.py", line 147, in send
    command, parameters, retry_count, extra_parameters=extra_parameters
  File "/home/dietpi/.local/lib/python3.7/site-packages/miio/miioprotocol.py", line 236, in send
    extra_parameters=extra_parameters,
  File "/home/dietpi/.local/lib/python3.7/site-packages/miio/miioprotocol.py", line 192, in send
    data, addr = s.recvfrom(1024)
```
Do you know what else could I try? Any hint would be appreciated

**Comment by edugrt** [comment]
Same here. Xiaomi 360 Camera CMSXJ13B
