### ISSUE TITLE
No response from device CMSXJ13A (IP & token are correct)

### ISSUE THREAD

**Issue by bombaata** [miguelangel-nubla/videoP2Proxy#28]
Hi, thanks for your work. I'm trying to use it for a CMSXJ13A device and got the following error :

```
Got error when receiving: timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/miio/device.py", line 179, in send
    command, parameters, retry_count, extra_parameters=extra_parameters
  File "/usr/local/lib/python3.6/dist-packages/miio/miioprotocol.py", line 237, in send
    extra_parameters=extra_parameters,
  File "/usr/local/lib/python3.6/dist-packages/miio/miioprotocol.py", line 237, in send
    extra_parameters=extra_parameters,
  File "/usr/local/lib/python3.6/dist-packages/miio/miioprotocol.py", line 237, in send
    extra_parameters=extra_parameters,
  File "/usr/local/lib/python3.6/dist-packages/miio/miioprotocol.py", line 241, in send
    raise DeviceException("No response from the device") from ex
miio.exceptions.DeviceException: No response from the device
Can't read output line 1 from command: python3 -c "import miio;result = miio.device.Device('192.168.0.99', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx').send('get_ipcprop', ['all']);print(result['p2p_id']);print(result['avID']);print(result['avPass']);"
Error connecting to camera, make sure ip and token are correct.
Error, waiting 10 seconds and trying again.
```

IP and token are OK, device is turned on.

**Comment by bombaata** [comment]
miiocli command reports _Error: Unable to discover the device_ for this model.
