### ISSUE TITLE
Please, add support to "XVV Smart Wifi PTZ Camera (XVV-6620S-Q8)"

### ISSUE THREAD

**Issue by wbrione** [miguelangel-nubla/videoP2Proxy#30]
python3 miottemplate.py print urn:miot-spec-v2:device📷0000A01C:xiaovv-xvsnowman:1.json
Device 'urn:miot-spec-v2:device📷0000A01C:xiaovv-xvsnowman:1': Camera with 3 services

    Service siid 1: (Device Information): 4 props, 0 actions

      ## Properties ##
              siid 1: piid: 1 (Device Manufacturer): (string, unit: None) (acc: ['read'])
              siid 1: piid: 2 (Device Model): (string, unit: None) (acc: ['read'])
              siid 1: piid: 3 (Serial Number): (string, unit: None) (acc: ['read'])
              siid 1: piid: 4 (Current Firmware Version): (string, unit: None) (acc: ['read'])

    Service siid 2: (Camera Control): 1 props, 0 actions

      ## Properties ##
              siid 2: piid: 1 (Switch Status): (bool, unit: None) (acc: ['read', 'write'])

    Service siid 3: (P2P Stream): 0 props, 2 actions

      ## Actions ##
              siid 3: aiid 1 Start P2P Stream: in: [] -> out: []
              siid 3: aiid 2 Stop Camera Stream: in: [] -> out: []

**Comment by wbrione** [comment]
videop2proxy --ip 192.168.1.135 --token ******** --rtsp 8554
Starting proxy...
Starting RTSP server on "rtsp://172.17.0.3:8554/"
(Using port 80 for optional RTSP-over-HTTP tunneling.)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/miio/device.py", line 179, in send
    command, parameters, retry_count, extra_parameters=extra_parameters
  File "/usr/local/lib/python3.7/dist-packages/miio/miioprotocol.py", line 214, in send
    self._handle_error(payload["error"])
  File "/usr/local/lib/python3.7/dist-packages/miio/miioprotocol.py", line 274, in _handle_error
    raise DeviceError(error)
miio.exceptions.DeviceError: {'code': -10000, 'message': 'user undefined error'}
Can't read output line 1 from command: python3 -c "import miio;result = miio.device.Device('192.168.1.135', '***********').send('get_ipcprop', ['all']);print(result['p2p_id']);print(result['avID']);print(result['avPass']);"
Error connecting to camera, make sure ip and token are correct.
Error, waiting 10 seconds and trying again.

But...

ping 192.168.1.135
PING 192.168.1.135 (192.168.1.135) 56(84) bytes of data.
64 bytes from 192.168.1.135: icmp_seq=1 ttl=63 time=6.37 ms
64 bytes from 192.168.1.135: icmp_seq=2 ttl=63 time=276 ms

Obviously the token is also correct, as it was used to extract the device metadata from the xiaomi platform

**Comment by febriyan1302** [comment]
same issue on me {'code': -10000, 'message': 'user undefined error'}

**Comment by Snakesms** [comment]
Did you check that the last commit to this repository had been made 3 years ago on 29 Sep 2018?
This project is not in development for a long time already. so nothing to hope about I'm afraid

**Comment by febriyan1302** [comment]
a little bit debugging, this project using python-miio, so yeah miio can't support my camera (Xiaomi mi camera ptz 2k pro)

<img width="947" alt="Screen Shot 2021-07-30 at 01 30 22" src="https://user-images.githubusercontent.com/18423871/127547198-b0b115bb-1ed2-47db-8122-04702d7fab09.png">

**Comment by febriyan1302** [comment]
wait, i corrected, it's support with miio 👍 mybe basic function..

<img width="1028" alt="Screen Shot 2021-07-30 at 01 41 31" src="https://user-images.githubusercontent.com/18423871/127548522-1d330ddf-ff63-4afd-bc6e-cc4935f7d010.png">
