### ISSUE TITLE
Xiaomi Mijia 1080P dont works

### ISSUE THREAD

**Issue by CooleRnax** [miguelangel-nubla/videoP2Proxy#6]
Stream doesn't work
```
Starting proxy...
Starting RTSP server on "rtsp://192.168.65.3:8554/"
(Using port 80 for optional RTSP-over-HTTP tunneling.)

Got error when receiving: timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 257, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 257, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 257, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 257, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 286, in send
    return self.send(command, parameters, retry_count - 1)
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 286, in send
    return self.send(command, parameters, retry_count - 1)
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 286, in send
    return self.send(command, parameters, retry_count - 1)
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 289, in send
    raise DeviceException("No response from the device") from ex
miio.exceptions.DeviceException: No response from the device
Can't read output line 1 from command: python3 -c "import miio;result = miio.device.Device('xxxxxxxxxxx', 'xxxxxxxxxxxxxxxxxxxxxxxxxxx').send('get_ipcprop', ['all']);print(result['p2p_id']);print(result['avID']);print(result['avPass']);"
Error connecting to camera, make sure ip and token are correct.
Error, waiting 10 seconds and trying again.
```

**Comment by joelhaasnoot** [comment]
Unfortunately same

**Comment by goncalossilva** [comment]
Same. Can I help debug this?

**Comment by ardeus-ua** [comment]
Same

**Comment by arturleao** [comment]
Same here unfortunately. This actually seems to mess the connection with the device, prior to running this I'm able to use miiocli to send commands to the camera and after running this, I can't reach the camera anymore, have to restart it (unplug and plug it again).

**Comment by edugrt** [comment]
Same here. Xiaomi 360 Camera CMSXJ13B
