### ISSUE TITLE
Xiaofang don't not work

### ISSUE THREAD

**Issue by Ziracul** [miguelangel-nubla/videoP2Proxy#7]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/miio/device.py", line 257, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/miio/device.py", line 257, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/.local/lib/python3.5/site-packages/miio/device.py", line 286, in send
    return self.send(command, parameters, retry_count - 1)
  File "/home/pi/.local/lib/python3.5/site-packages/miio/device.py", line 286, in send
    return self.send(command, parameters, retry_count - 1)
  File "/home/pi/.local/lib/python3.5/site-packages/miio/device.py", line 286, in send
    return self.send(command, parameters, retry_count - 1)
  File "/home/pi/.local/lib/python3.5/site-packages/miio/device.py", line 289, in send
    raise DeviceException("No response from the device") from ex
miio.exceptions.DeviceException: No response from the device
Can't read output line 1 from command: python3 -c "import miio;result = miio.device.Device('192.168.1.78', '58686745624155706865793972764530').send('get_ipcprop', ['all']);print(result['p2p_id']);print(result['avID']);print(result['avPass']);"
Error connecting to camera, make sure ip and token are correct.
Error, waiting 10 seconds and trying again.

**Comment by Raidok** [comment]
Don't waste your time on that. I investigated it and it seems that p2p_id, avID and avPass are not available any more.
Use [samtap/fang-hacks](https://github.com/samtap/fang-hacks) for legacy cube cam or [EliasKotlyar/Xiaomi-Dafang-Hacks](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks) if you have the 1S model and get an RTSP stream straight from the camera itself.
